baseURL: "https://www.jmaxkanter.com/"
languageCode: "en-us"
title: "Max Kanter"
theme: "jmaxkanter.com"
buildDrafts: true
params:
  og_image: "/open-graph.jpg"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true
    renderer:
      unsafe: true
