baseURL: "https://www.jmaxkanter.com/"
languageCode: "en-us"
title: "Max Kanter"
theme: "jmaxkanter.com"
buildDrafts: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true